# coding=utf-8
x = set('abcde')
y = set('dexyz')
print(x - y)
print(x & y)
print(x | y)
print(x ^ y)
print('e' in x)
print(x > y, x < y)
print(x)
print(y)
z = x.intersection(y)
print(z)
z.add('hello')
print(z)
z.update(set(['X', 'Y']))
print(z)
z.remove('X')
print(z)
t = set(['Y'])
print(z.issubset(['Y']))
print(t.issubset(z))
# 3.+支持花括号声明集合
z = {'a', 'b', 'c'}
print(z)
print(type(z))
print(type({}))
print(type(set()))
print(z.union(['1', '2']))
# 不支持的运算操作，可通过内置方法实现
# print(z | ['1', '2'])
